spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/trans
    username: root
    password: 11111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: false